### ISSUE TITLE
给 无法自己重签名的V2SignApk包 提供一个强制diff工具

### ISSUE THREAD

**Issue by sisong** [sisong/ApkDiffPatch#12]
理论上，只要当前zlib库（或者收集的其他常见兼容库）能够匹配上部分newApk的压缩编码输出（反算出压缩参数），就能降低部分补丁大小；    
old apk 分为是否V2签名的情况分别处理（无v2签名的不能够过于信任其不会简单变动）；      
new apk对每个文件区分匹配压缩参数；     
   
 补丁大小最差情况接近HDiffPatch或BsDiff的结果，最好结果接近ApkDiffPatch中ZipDiff的结果；   
patch速度因为压缩参数的原因，可能会比较慢；

**Comment by simonking200** [comment]
您好，首先非常感谢您能够分享HDiffPatch这个非常棒的库，我现在使用的是HDiffPatch，目前我也遇到的这样的实际问题，一般渠道会从新组包生成很多子渠道。组包过程又是从安装目录中获取，这时候获取的包已经是子渠道包了，所以这个Patch理论上应该是不成功的，不知道这个问题如何解决，还请解惑。

**Comment by simonking200** [comment]
您好，首先非常感谢您能够分享HDiffPatch这个非常棒的库，我现在使用的是HDiffPatch，目前我也遇到的这样的实际问题，一般渠道会从新组包生成很多子渠道。组包过程原包又是从安装目录中获取的，这时候获取的包已经是子渠道包了，所以这个Patch理论上应该是不成功的，不知道这个问题如何解决，还请解惑

**Comment by sisong** [comment]
“收集的其他常见兼容库”并尝试，代价比较大，库的版本修改造成的编码变化的风险也较大；       
另一个思路： 可以只包含一套库，但在diff数据中保存一些给重新编码时最少的“指导”数据，使得编码能够还原，并且压缩编码运行的更快。

**Comment by sisong** [comment]
# sf_patch 进展:
a C++ library and command-line tools for archivefile Diff & Patch;create sf_patch's format delta/differential between zip(apk,jar,gz,tar) files; stable & fast to patch archive,support muti-thread patch;
( dependent libraries [HDiffPatch], [zlib], [lzma]. )   

[ApkDiffPatch]: https://github.com/sisong/ApkDiffPatch
[HDiffPatch]: https://github.com/sisong/HDiffPatch
[zlib]: https://github.com/madler/zlib
[lzma]: https://www.7-zip.org/sdk.html
[BsDiff]: http://www.daemonology.net/bsdiff/
[xdelta3]: https://github.com/jmacd/xdelta
[archive-patcher]: https://github.com/google/archive-patcher

## Diff & Patch Benchmark 
### test algorithms:
[BsDiff] and [xdelta3] and [HDiffPatch] are diff algorithm for binary;   
[archive-patcher] and [ApkDiffPatch] and [sf_patch] are diff algorithm for zip file;    
```
BsDiff          : v4.3
xdelta3         : v3.1
HDiffPatch      : v3.0.9
archive-patcher : v1.1   (used in google play store, test by https://github.com/googlesamples/apk-patch-size-estimator )
ApkDiffPatch    : v1.3.2 (for diff apk file,it's signed by self)
sf_patch        : v0.9.7 (for diff any zip file)
```
### test cases:
test apk files, sum new size 728,112,076 bytes

|old version|new version|new size|
| :----- | :----- | -----: |
|chrome-63-0-3239-111.apk|chrome-64-0-3282-123.apk|43,879,588|
|chrome-64-0-3282-123.apk|chrome-64-0-3282-137.apk|43,879,588|
|chrome-64-0-3282-137.apk|chrome-65-0-3325-109.apk|43,592,997|
|google-maps-9-70-0.apk|google-maps-9-71-0.apk|50,568,872|
|google-maps-9-71-0.apk|google-maps-9-72-0.apk|54,342,938|
|weixin662android1240.apk|weixin663android1260.apk|63,595,326|
|weixin663android1260.apk|weixin665android1280.apk|63,669,882|
|jd8.5.12.apk|jd9.0.0.apk|96,891,703|
|taobao9.7.2.apk|taobao9.8.0.apk|178,734,456|
|meituan10.9.203.apk|meituan10.9.401.apk|88,956,726|
   
### test results:   
note: The statistical run time of [archive-patcher] does not include compress/decompress patchFile time;   
note: when compiling BsDiff, suffix string index type int64 changed to int32, faster and memroy requires to be halved!   
MT means muti-thread, all time used second, require memroy used MB, and average value by case.   

|algorithm|download size|ratio|diff time|diff memroy|patch time|patch memroy|MT-patch time|MT-patch memroy|
| :----- | -----: | ----: | ----: | ----: | -----: | -----: | ----: | ----: |
|no diff|728,112,076|100.0%| | | | | | |
|BsDiff +bzip2|415,171,951|57.0%|104|652|2.4|155| | |
|xdelta3|416,937,505|57.3%|16|233|0.4|106| | |
|HDiffPatch -m-1 +zlib|410,930,412|56.4%|56|442|0.2 |17| | |
|HDiffPatch -s-16 +zlib|413,806,477|56.8%|5|83|0.2 |17| | |
|archive-patcher +zlib|219,939,278|30.2%|123|1,574|6.5|78| | |
|archive-patcher +lzma2|187,460,275|25.7%|127|1,579|6.6|78| | |
|ApkDiffPatch +zlib|173,385,068|23.8%|58|778|5.0|4|2.5|95|
|ApkDiffPatch +lzma|150,811,943|20.7%|58|778|5.3|15|3.1|107|
|sf_patch -o-0 +zlib|411,041,347|56.5%|56|477|0.4|2|0.3|3|
|sf_patch -o-0 +lzma2|409,623,863|56.3%| 62|638|0.8|19|0.6|19|
|sf_patch -o-1 +zlib|240,039,786|33.0%|50|746|1.7|5|1.1|8|
|sf_patch -o-1 +lzma2|223,862,719|30.7%|54|802|2.4|18|1.5|22|
|sf_patch -o-2 +zlib|176,938,492|24.3%| 57|977|6.5|5|1.5|14|
|sf_patch -o-2 +lzma2|154,294,071|21.2%|59|988|6.9|19|1.8|27|

**Comment by sisong** [comment]
tool： https://github.com/sisong/sfpatcher  
close this issue
