### ISSUE TITLE
能不能提供一份最新的Android ndk编译mk文件啊

### ISSUE THREAD

**Issue by lhholylight** [sisong/ApkDiffPatch#36]
我有看到issues #17,但是上面提供的mk文件跟现在的项目根本对不上，不知道具体指向的是哪些文件

**Comment by sisong** [comment]
近期会提供一个demo，参见 #35    
不知道哪些文件的话，你也可以参考 Makefile 文件中 “ZipPatch: ”那一段

**Comment by sisong** [comment]
已经提交了Patch的mk，在 [builds/android_ndk_jni_mk/](https://github.com/sisong/ApkDiffPatch/blob/master/builds/android_ndk_jni_mk/)
