### ISSUE TITLE
生成新包失败问题

### ISSUE THREAD

**Issue by h923745834** [sisong/ApkDiffPatch#42]
大佬你好，
我在libs里添加了armea-v7a/libapkpatch.so.加载so文件也成功。
在Activity oncreate(）调用
ApkPatch.patch(oldApkPath, oldDiffpath, newApkpath,maxUncompressMemory,tempUncompressFilePath,1)
参数：
 String root = Environment.getExternalStorageDirectory().getAbsolutePath();
        String oldApkPath = root+"/1/old.apk";
          String oldDiffpath = root+"/1/add.diff";
          String newApkpath = root+"/1/new.apk";
          long maxUncompressMemory = 8*1024*1024;//8mb
          String tempUncompressFilePath=root+"/360/";
没有生成新包，返回值1。

**Comment by sisong** [comment]
返回1(也就是PATCH_OPENREAD_ERROR)， 说明文件无法访问到；    
另外tempUncompressFilePath参数应该是一个文件名，而不能是目录；

**Comment by h923745834** [comment]
临时解压文件已改成
String tempUncompressFilePath=root+"/360/temp";
之前都是访问权限问题，现在返回 7，有生成新文件，但0B.
我调试是读写权限都有了。不知什么问题？

**Comment by h923745834** [comment]
@sisong

**Comment by sisong** [comment]
你自己可以看返回值（TPatchResult）是什么意思的，7是PATCH_COMPRESSTYPE_ERROR，表示解压缩插件和压缩类型不匹配（或者add.diff的数据有误）；

**Comment by h923745834** [comment]
@sisong 周一好，确认了一下，我们后端是 使用hdiffz -s -d yqqs_v1.3.2.apk yqqs_v1.4.2.apk yqqs.diff
来生成这个差分包的。在后端他们测试是可以合成正确的新包。这样是不是说前端解压方式不对？如果不对，前后端分别使用哪个工具呢？

**Comment by sisong** [comment]
**你用错工具了**： hdiffz和hpatchz对应；而ApkNormalized+ZipDiff和ZipPatch对应 (这是针对apk、zip文件格式的优化版)；  libapkpatch.so是ZipPatch的android库；    
hpatchz的android库需要你自己编译，只裁剪出自己需要的那一部分功能来生成so；

**Comment by h923745834** [comment]
哪套工具比较合适已上线应用？我看了一下apkDiffPatch比较高效

**Comment by sisong** [comment]
我们在Andoroid上用的ApkDiffPatch这套；  在PC上用的HDiffPatch这套（支持目录diff&patch）；
