### ISSUE TITLE
ApkNormalized 损坏zip文件

### ISSUE THREAD

**Issue by JemmyLoveJenny** [sisong/ApkDiffPatch#46]
我们都是中国人，那我就不写英语了……xD
我发现 ApkNormalized 有两点问题：
1. 重压缩的结果不一致（报错）
2. 生成的zip文件 不符合zip文件标准

我以`release`中已编译好的`hdiffpatch_v3.0.8_ApkDiffPatch_v1.3.1_bin_beta.zip`为例

第一个问题出现在 Win64 版本ApkNormalized中，处理到最后会报错
```
UnZipper_fileData_decompressTo(srcZip,srcIndex,&stream) ERROR!
ApkNormalized result file check ERROR!
```
Win32版本和Linux64版本的执行结果相同，也不报错，其他版本没测试
我还没找出出问题的地方，不过我觉得这个问题不太大…应该是不同平台的数据类型长度变化导致的，改用定长类型`int8_t`,`uint32_t`等等应该就可以解决了

第二个问题 的现象就是ZIP文件损坏
用十六进制编辑器查看normalized的zip文件，会发现在PK头部之前多出来了4-6个空字节
把那几个00字节删掉之后，zip文件也不正确，但是具体哪里不正确我也没找出来（我不熟悉zip结构）
反正我用7-zip打开压缩包后无法修改或删除文件（7-zip提示“只读”，那意味着文件结构损坏，只能够读取，不能修改）

**Comment by sisong** [comment]
收到你的报告，会跟进处理

**Comment by sisong** [comment]
1. win64版ApkNormalized.exe报错的问题      
 从错误文字来看，是在第二次打开源zip文件和生成的zip文件对比数据时，解压源zip失败；    
 我在macos上用wine运行相同的测试， 运行正常；我手边没有真正的win64环境来测试；    
1.  PK头部之前多出几个空字节的问题   
 这是为了数据对齐造成的；每个entry都用一个“PK..”来表明一个新的entry开始；为了优化每个entry正文数据的起始偏移为8字节(不是zip规范必须，但某些系统如果有该对齐就能支持正文数据的内存映射)，就需要在前面填充一些0数据来补齐； 这里有两个选择，要么修改该entry的某个属性，扩大其长度，要么就得在PK前填充一些0数据；  我选择了后面这一种，基于这样的想法：不改变原entry的任何属性值；（因为从我理解的文献规范来说，entry可以任意放置位置，之间也可以有任意长的空隙；） 这就造成和部分工具的假设(第一个entry一定出现在0位置的期待)不兼容了;      
    要解决这个兼容问题，就得针对第一个entry特殊处理，要不放弃对齐策略，要不修改或添加某个属性值(增大其长度)。

**Comment by JemmyLoveJenny** [comment]
1. 关于win64版ApkNormalized报错问题
我尝试复现该问题，发现这个问题和apk文件有关，并不是所有都会出错
但是我出错的那个文件大小450M，也不太好上传上来，我再研究一下出错条件吧……

2. 空字节问题
那就是说你normalized过的zip文件 在每个record之间都有数量不一的空字节
按照zip标准的读取方法，从EndOfCentralDirectory开始解析zip文件就不会出错…？
其实这个 空字节 照理来说没关系，但是关键在于 Android 系统不识别这种apk包

**Comment by JemmyLoveJenny** [comment]
zip文件结构`[文件头+文件数据+数据描述符]{此处可重复n次}+核心目录+目录结束标识`
你是说其中的 `文件数据` 需要8字节对齐？
我不太理解为什么文件数据内存映射…把文件头8字节对齐之后再取出文件数据偏移不可以吗？
还有我试了一下zipalign的对齐策略，好像是文件头对齐而不是数据对齐

**Comment by JemmyLoveJenny** [comment]
Win64版本出错的位置是在
`Zipper.cpp:560` `UnZipper_fileData_decompressTo(srcZip,srcIndex,&stream)`
check_clear那里报错的

**Comment by JemmyLoveJenny** [comment]
进一步调试发现 `decompress_plugin_demo.h`的`_zlib_is_decompress_finish`函数中
指针`self`转换为`_zlib_TDecompress*`类型，其中`self->code_begin=471279714`,`self->code_end=471279716`
因为`code_begin!=code_end`，所以返回值是0

我根据解压前后的Size找到了这个文件，它就是`META-INF/MANIFEST.MF`，不过不是在源文件中，而是在normalized的zip中，文件头中写的compressedSize比 解压消耗的compressedSize大了 2
我在normalized的zip中找到对应的位置，多余的两个字节为 0xFF,0x02 如图
![捕获](https://user-images.githubusercontent.com/37937841/74720191-55f29f00-5270-11ea-97fc-d1b34403c230.PNG)

**Comment by JemmyLoveJenny** [comment]
我提取deflate数据正文(code_begin到code_end)，用.Net的`System.IO.Compression.DeflateStream`解压
验证结果：无论末尾两字节0xFF,0x02是否存在，deflate解压结果都与原文件相同

**Comment by JemmyLoveJenny** [comment]
https://github.com/sisong/HDiffPatch/blob/d3c46cb22c05d05386b57fd7a676c4634eae99c6/decompress_plugin_demo.h#L160
在以上地方看到`readLen=dec_buf_size`，

https://github.com/sisong/HDiffPatch/blob/d3c46cb22c05d05386b57fd7a676c4634eae99c6/decompress_plugin_demo.h#L90
https://github.com/sisong/HDiffPatch/blob/d3c46cb22c05d05386b57fd7a676c4634eae99c6/decompress_plugin_demo.h#L108-109
以上可知，`sizeof(_zlib_TDecompress)`变化会导致`readLen`变化
少读了那两个字节之后，解压出的数据长度刚好等于UncompressedSize
https://github.com/sisong/ApkDiffPatch/blob/master/src/patch/Zipper.cpp#L553-559
然后就在此跳出了循环，没有在循环读一次那两个字节

**Comment by JemmyLoveJenny** [comment]
我分析的结果就是这些了，我给你一个实例吧，你自己也可以研究看看。
你用Win64版本的ApkNormalized处理它，就会有报错了
[MANIFEST.zip](https://github.com/sisong/ApkDiffPatch/files/4218920/MANIFEST.zip)

**Comment by sisong** [comment]
谢谢你提供的翔实信息和测试用例！！！

> 关键在于 Android 系统不识别这种apk包   

  是的，所以需要发一个修改版，更改规范化逻辑，这个修改不会破坏原有的patch逻辑；       

> zipalign的对齐策略，好像是文件头对齐而不是数据对齐   

 zipalign是数据对齐的，zipalign会修改entry的扩展字段，我的修改也在特殊情况下(没有非签名压缩entry时)需要修改第一个entry的扩展字段来满足PK必须在开头的约束；    

> Win64版本出错    

 readLen和缓存区的大小不同并没有什么关系，代码看不出什么问题； 反而是那多出来的`无用`的2个字节比较奇怪，这破坏了一个假设：`解压出所有数据的时候应该正好消耗掉所有编码`，造成`_zlib_is_decompress_finish`的判断失败（readLen不同正好触发了这个假设，我没有win64环境，macos下想复现这个条件还没有成功）   
还需要继续跟进

**Comment by JemmyLoveJenny** [comment]
> 缓存区的大小不同并没有什么关系

嗯，我又看了一下确实没有关系，生成的文件也相同
但是这个错误的原因就很令人迷惑了

> zipalign是数据对齐的

官方说zipalign之后的apk可以提高运行效率……那么官方所指的对齐需要PK头也对齐吗？
而且好像ApkNormalized之后并没有对齐……因为在我所说的这里
> 其中`self->code_begin=471279714`,`self->code_end=471279716`

`code_end=471279716`,`compressedSize=475306`,因此原始的`code_begin=470804410`
然而470804410明显没有8字节对齐吧…？

**Comment by sisong** [comment]
压缩后的数据不需要对齐

**Comment by JemmyLoveJenny** [comment]
> 压缩过的数据不需要对齐，其他的entry数据区才需要对齐；

你的意思是说`ZipFileRecord`不用对齐，需要对齐的是`ZipDirEntry`？
我没听懂…能否在图片中解释说明一下需要对齐的部分 这个zip已经被normalized过了
![捕获](https://user-images.githubusercontent.com/37937841/74752933-5d369e80-52aa-11ea-8174-22f4060a0ffa.PNG)

**Comment by sisong** [comment]
> 我好像明白了…你的意思是说Entry中压缩方式为STORED(0)的文件才需要对齐？
储存压缩过的数据的entry不需要对齐，其他entry（甚至dir和0大小文件）都需要对齐，这是用zipalign检查对齐时得到的信息；
