### ISSUE TITLE
path 之后的新文件和原来的新文件 md5 会一样吗？

### ISSUE THREAD

**Issue by jxdeng3264** [sisong/ApkDiffPatch#48]
比如两个apk
apk1.0 
apk2.0  diff文件  diff1-2

./ZipPatch  apk1.0  diff1-2  newapk2.0

得到的 newapk2.0 和 apk2.0   MD5 是一样的吗？

**Comment by sisong** [comment]
你可以下载我编译出来的可执行程序来测试： https://github.com/sisong/ApkDiffPatch/releases   
 1. 需要使用里面的 ApkNormalized来处理apk文件；
 1. 处理的结果需要用android sdk的签名程序重新签名，签名后的包就是release的包了；    
 1. 然后就能执行ZipDiff了，diff完成后会调用ZipPatch来检查oldApk+diff补丁合成的新apk文件是否和release的包二进制完全相同；
