### ISSUE TITLE
没理解这句说明

### ISSUE THREAD

**Issue by jxdeng3264** [sisong/ApkDiffPatch#49]
if your apk used Apk v2 sign(or Apk v3 sign), Released newZip := AndroidSDK#apksigner(ApkNormalized(newZip)) before ZipDiff;

AndroidSDK#apksigner 是指的哪个方法吗？

**Comment by sisong** [comment]
这是安卓SDK里的签名命令行工具，比如   Android/sdk/build-tools/27.0.3/apksigner

**Comment by jxdeng3264** [comment]
我测试的时候：
ApkNormalized  file1.0.apk   nor.file1.0.apk
ApkNormalized  file2.0.apk   nor.file2.0.apk

然后对 nor.file1.0.apk nor.file2.0.apk  两个文件进行 diff  ，再进行 patch，  patch 之后的文件会安装失败。
=======
**可以做到不用 Android sdk 工具重新签名， 而是在代码里面 ApkNormalized  然后 Diff 得到差异文件 吗？**最后做到能成功安装。

**Comment by jxdeng3264** [comment]
我测试的时候：
ApkNormalized file1.0.apk nor.file1.0.apk
ApkNormalized file2.0.apk nor.file2.0.apk
然后对 nor.file1.0.apk nor.file2.0.apk 两个文件进行 diff ，再进行 patch， patch 之后的文件会安装失败。

可以做到不用 Android sdk 工具重新签名， 而是在代码里面 ApkNormalized 然后 Diff 得到差异文件 吗？  

最后做到能成功安装。

**Comment by jxdeng3264** [comment]
我测试的时候：
ApkNormalized file1.0.apk nor.file1.0.apk
ApkNormalized file2.0.apk nor.file2.0.apk
然后对 nor.file1.0.apk nor.file2.0.apk 两个文件进行 diff ，再进行 patch， patch 之后的文件会安装失败。

可以做到对V2签名的文件，不用ApkNormalized  之后， Android sdk 工具重新签名， 而是在代码里面 ApkNormalized ，调用 jni 的 签名函数之类的。然后 Diff 得到差异文件 吗？

最后就一步到位，不用再次去签名。

**Comment by sisong** [comment]
ApkNormalized去调用apksigner或者去实现签名，耦合太重；    
apksigner和ApkNormalized都是命令行工具，你写个批处理脚本不就一样了
