### ISSUE TITLE
编译后的可执行文件

### ISSUE THREAD

**Issue by jxdeng3264** [sisong/ApkDiffPatch#50]
你好：
      我下了hdiffpatch_v3.0.8_ApkDiffPatch_v1.3.2_bin_beta 这个包，
运行 ZipDiff 和 ZipPatch 之后，V2签名的apk 不能正常安装。但是
我试了
hdiffz.exe
hpatchz.exe
可以！
所以想问下， 这两个文件是怎么通过源码编译生成的？

**Comment by sisong** [comment]
“V2签名的apk 不能正常安装”   当然不能，需要`Released newZip := AndroidSDK#apksigner(ApkNormalized(newZip))`，才能保证生成的apk二进制相同；    

“这两个文件是怎么通过源码编译生成的？”   hdiffz和hpatchz是[HDiffPatch](https://github.com/sisong/HDiffPatch)这个仓库生成的；       
   
HDiffPatch的实现只是把文件输入看作2块二进制数据，来执行diff&patch；  ApkDiffPatch是把2个zip文件解压缩后调用HDiffPatch来实现的；
