### ISSUE TITLE
Android中使用ZipPatch问题

### ISSUE THREAD

**Issue by linguangyu1996** [sisong/ApkDiffPatch#54]
在安卓使用so文件，对于patch方法：
public static native int patch(String oldApkPath,String patchFilePath,String outNewApkPath,
                                   long maxUncompressMemory,String tempUncompressFilePath,int threadNum);

1、请问 maxUncompressMemory、tempUncompressFilePath这两个参数是用于解压的时候使用的临时最大存储空间和该存储空间的路径吗？对于这个的空间分配和进行oldZip，diffZip，newZip文件的大小有最优的映射吗？这个问题和上面的那个线程数量的问题类似。

2、我在使用的合成1G的文件的时候分配了1024 *10空间，但是在合成的整个过程中（运行中和运行后）并没有看到我指定的路径下面有该临时文件的生成，这是什么原因呢？

**Comment by sisong** [comment]
`maxUncompressMemory`的意思是当  引用旧文件需要的解压内存(ref old decompress)大于这个设置值的时候，就使用tempUncompressFilePath这个临时文件来代替这个内存占用；      
“分配了1024 *10空间,...没有看到...该临时文件的生成”   你的理解应该没有错，我也不知道是什么情况； 只能初步说没有超过10k的解压数据？

**Comment by linguangyu1996** [comment]
thx，我这边再对这个情况进行测试，看看是什么原因
