### ISSUE TITLE
ZipDiff问题

### ISSUE THREAD

**Issue by linguangyu1996** [sisong/ApkDiffPatch#55]
在进行ZipDiff的时候命令行显示部分如下：
----------------------------------------------------------------------
ZipDiff with compress plugin: "lzma"
ZipDiff same file count: 1184 (all 1977)
    diff new file count: 793
     ref old file count: 1778 (all 1833)
     ref old decompress: 19 file (16931246 byte!)

run hdiffz:
  oldDataSize : 25320411
  newDataSize : 70138231
  (used one lzma dictSize: 393216  (input data: 300626))
  (used one lzma dictSize: 3145728  (input data: 2414172))
  (used one lzma dictSize: 3145728  (input data: 2934300))
  (used one lzma dictSize: 4194304  (input data: 49753616))
  diffDataSize: 25113120
  diff  time: 34.109 s
  hpatchz check hdiffz result ok!
  patch time: 1.297 s

  (used one lzma dictSize: 6144  (input data: 4236))
ZipDiff size: 25113495
ZipDiff time: 40.047 s

run ZipPatch:
  check ZipPatch result Same Like ok! (but not Byte By Byte Equal)
  patch time: 5.078 s

all     time: 45.125 s
------------------------------------------------------------------------------
问题一：

请问其中4个dictSize：
  (used one lzma dictSize: 393216  (input data: 300626))
  (used one lzma dictSize: 3145728  (input data: 2414172))
  (used one lzma dictSize: 3145728  (input data: 2934300))
  (used one lzma dictSize: 4194304  (input data: 49753616))
这4个的大小是怎么确定的？和什么有关？我这边是否可以自行定义大小？

-----------------------------------------------------------------------------------
问题二：

请问在出现了4个dictSize并显示diff完成之后还出现了：
 (used one lzma dictSize: 6144  (input data: 4236))
这个的作用是什么呢？是否会计入patch时候的空间复杂度计算中？大小是由什么决定的呢？

**Comment by sisong** [comment]
1.  控制字典大小，你需要修改源代码，最大字典尺寸由这句代码控制：  `myLzmaCompressPlugin.dict_size=(1<<20)*4;`     
当输入数据小于最大字典的时候，默认字典大小是交给lzma库决定的；如果你想自由的根据输入数据大小设置字典大小，可以修改这几行代码：
``` 
        props.dictSize=dictSize;
        props.reduceSize=in_data->streamSize;
        props.numThreads=plugin->thread_num;
        LzmaEncProps_Normalize(&props);
```  
props.dictSize的值根据in_data->streamSize的值来自己设定；      

2.  “这个的作用是什么呢？是否会计入patch时候的空间复杂度计算中？”    这是一些存储在补丁包中的元数据，比如文件名、大小、位置等之类的，压缩后储存的；   patch前会被解压；

**Comment by linguangyu1996** [comment]
请问上述的需要修改的代码在哪个目录下的哪个文件呢？

**Comment by sisong** [comment]
你不能搜索文本吗:(    
在：   
ApkDiffPatch/src/diff/Differ.cpp   
ApkDiffPatch/HDiffPatch/compress_plugin_demo.h

**Comment by linguangyu1996** [comment]
thx，notepad++的查找模式设置错误，开始没有查找成功
