### ISSUE TITLE
关于Apk差分和合成过程中设置忽略文件的问题

### ISSUE THREAD

**Issue by linguangyu1996** [sisong/ApkDiffPatch#60]
您好，请问：
      
        - 如果我在对APK进行差分和合成的过程中是否能够指定对某些文件进行忽略呢？
        - 如果没有这个参数的话我是否能够在源码中能够有对应的处理的逻辑进行修改源码呢？例如我需要忽略APK文件中的Zip Comment的内容，或者忽略META-INF文件夹中指定的文件。有办法可以做到吗？

感谢~

**Comment by sisong** [comment]
库没有提供“设置忽略文件”的功能；   
apk是一个整体，我不知道忽略某些文件在实际中有何具体意义？     
忽略的意思是跳过？还是仅仅不解压？  是在ApkNormalized中忽略还是在ZipDiff中忽略？

**Comment by linguangyu1996** [comment]
1、在实际过程中会因为某些原因导致有很多APK包，但是这些APK包只存在一个文件或者Zip Comment中注释内容的差别，这时候如果能够指定忽略某些特定文件的话，就可以针对这些差异性很小的apk只进行一次的diff，得出一个diff包之后这些apk都可以使用这个diff包进行合成。
     举例：有两个APK为：old.apk，new.apk ，我先用着两个apk进行diff得出一个差分包：old_new.diff，之后我在old.apk中的META-INF文件中添加了一个test.txt文件（因为签名文件中添加新文件不会改变APK整体逻辑），这时候为old(test).apk。如果我可以设置忽略test.txt文件，即在合成的时候直接将该文件拷贝到合成的全量包中，这样的话我可以用上述的old_new.diff和这个
old(test).apk合成一个new(test).apk，这个new(test).apk中META-INF文件夹下存在test.txt文件。

2、忽略的意思是代表在ZipDiff的时候不检查这个文件的差异，在ZipPatch的时候直接将old.apk中的拷贝到new.apk中。有点类似在ZipDiff的过程中标记了old.apk中的指定文件（如上述的test.txt）为new.apk中也有一份相同的文件，然后在patch的过程中就将old.apk中的这个文件引用到new.apk中

**Comment by sisong** [comment]
了解你的意思了；  我们也遇到过类似需求：不同渠道使用略微不同的apk包用来标记；虽然apk不同，但我们使用原始包来生成的diff补丁适用于所有渠道包；   
不过我们用的方案是在apk的v2签名区中添加，如果只有v1签名时就放在Central directory区域前面，代码中的功能可以参考： [ZiPatExtraDemo.cpp](https://github.com/sisong/ApkDiffPatch/blob/master/src/ZiPatExtraDemo.cpp)

**Comment by linguangyu1996** [comment]
方案：我们这边用的是v1签名，不过我们的对于不同渠道之间的略微不同的使用的标记的是直接在签名文件META-INF中保存一个文件的，该文件会记录渠道信息，或者是直接在Zip comment中添加渠道标识的注释。（这个方案是项目组统一的方案应该不能改变了）

需求：根据我们上述的方案的话可能就需要在对上述方案中的文件进行忽略。我理解的是原本diff的逻辑是如果我的old.apk中的META-INF文件中添加了一个test.txt文件，而我的new.apk中没有存在该文件，这时候diff生成的diff包中会有标记这个文件是在使用old.apk和diff合成的过程中是不需要使用的（当然这是我的理解不知道准不准确）。那是否可以修改diff包的信息将META-INF文件夹中的test.txt文件标识成是在patch过程中需要使用到合成new.apk的过程中来的呢？

**Comment by sisong** [comment]
仓库中有一个功能可能能够满足你们的需求： 开启宏 _IS_NEED_VIRTUAL_ZIP=1       
它的作用是在patch时 用自己的数据替换zip中entry文件的数据；    
diff时用原始zip文件创建补丁（假设是一个空的data.txt文件）；
patch时(即函数VirtualZipPatch)利用虚拟功能将加载到的有渠道数据的data.txt文件虚拟成空文件来完成任务；  参数`IVirtualZip_in* virtual_in`可以让你注册需要虚拟old_zip中的文件，参数`IVirtualZip_out* virtual_out`可以让你注册拦截写new_zip的每个entry文件；    
  _IS_NEED_VIRTUAL_ZIP当前不能凭空增删文件；

**Comment by linguangyu1996** [comment]
对这方面了解不多，所以不是太了解上面的意思，是说我可以先用一个空文件夹data.txt放在原始包中，然后进行diff得出一个diff文件，然后在patch的时候利用这个diff文件和old.apk（这个apk中的data.txt文件是有渠道数据的），但是将这个文件虚拟成空文件，这时候在patch的时候就会将这个文件从old.apk中拷贝过来。
-------是这个意思吗？

**Comment by sisong** [comment]
`是说我可以先用一个空文件夹data.txt放在原始包中，然后进行diff得出一个diff文件，然后在patch的时候利用这个diff文件和old.apk（这个apk中的data.txt文件是有渠道数据的），但是将这个文件虚拟成空文件`    到这里都正确，但结果不会copy那个渠道文件，生成的apk该data.tx文件也是一个空文件；   这里建议自己先将渠道信息保存起来使用，就可以避免丢失渠道信息的问题了；

**Comment by linguangyu1996** [comment]
那想实现这个功能能大概怎么实现呢？需要怎么改动源码才能对应到android中使用呢？对C/C++这方面没什么经验，向大神您取经。类似这个
![image](https://user-images.githubusercontent.com/25027872/81927954-12ad8f80-9617-11ea-9125-46cec9e18871.png)参数不太了解怎么传参

**Comment by sisong** [comment]
用到android的例子可以参考： https://github.com/sisong/ApkDiffPatch/tree/master/builds/android_ndk_jni_mk     
我在项目 [UnityAndroidHotUpdate](https://github.com/sisong/UnityAndroidHotUpdate) 中也用到了这个函数可以参考。     
   
哎 这个找你身边熟悉C/C++的人吧

**Comment by linguangyu1996** [comment]
好的，谢谢大佬，我这边熟悉一下，大佬这个issue可以先不关这个issue哈，之后有问题可以咨询大佬
