### ISSUE TITLE
ZipDiff过程中对ApkNormalized文件进行差分检测错误

### ISSUE THREAD

**Issue by linguangyu1996** [sisong/ApkDiffPatch#66]
输出部分日志如下：

oldZip  :"2_3_nor.apk"
newZip  :"1_2_nor.apk"
outDiff :"patch.diff"
  NOTE: oldZip found JarSign(ApkV1Sign)
  NOTE: newZip maybe normalized
  NOTE: newZip found JarSign(ApkV1Sign)

其中2_3_nor.apk和1_2_nor.apk都是进过normalized之后的文件，但是只有一个newZip maybe normalized，我看源码中有如下源码：

static bool checkZipInfo(UnZipper* oldZip,UnZipper* newZip){
    bool isOk=true;
    if (oldZip->_isDataNormalized)
        printf("  NOTE: oldZip maybe normalized\n");
    if (UnZipper_isHaveApkV1_or_jarSign(oldZip))
        printf("  NOTE: oldZip found JarSign(ApkV1Sign)\n");
    if (UnZipper_isHaveApkV2Sign(oldZip))
        printf("  NOTE: oldZip found ApkV2Sign\n");
    if (UnZipper_isHaveApkV3Sign(oldZip))
        printf("  NOTE: oldZip found ApkV3Sign\n");
    if (newZip->_isDataNormalized)
        printf("  NOTE: newZip maybe normalized\n");
    if (UnZipper_isHaveApkV1_or_jarSign(newZip))
        printf("  NOTE: newZip found JarSign(ApkV1Sign)\n");
    bool newIsV2Sign=UnZipper_isHaveApkV2Sign(newZip);
    if (newIsV2Sign)
        printf("  NOTE: newZip found ApkV2Sign\n");
    if (UnZipper_isHaveApkV3Sign(newZip))
        printf("  NOTE: newZip found ApkV3Sign\n");
    
    if (newIsV2Sign&(!newZip->_isDataNormalized)){
        //maybe bring apk can't install ERROR!
        printf("  ERROR: newZip not Normalized, need do "
               "newZip=AndroidSDK#apksigner(ApkNormalized(newZip)) before running ZipDiff!\n");
        isOk=false;
    }
    if ((!newIsV2Sign)&&UnZipper_isHaveApkV2orV3SignTag_in_ApkV1SignFile(newZip)){
        //maybe bring apk can't install ERROR!
        printf("  ERROR: newZip fond \"X-Android-APK-Signed: 2(or 3...)\" in ApkV1Sign file, need re sign "
               "newZip:=AndroidSDK#apksigner(newZip) before running ZipDiff!\n");
        isOk=false;
    }
    printf("\n");
    return isOk;
}

按照源码应该是有NOTE: oldZip maybe normalized输出的才是，这是什么原因呢？

**Comment by sisong** [comment]
应该是代码中故意将oldZip的_isDataNormalized标志设置成了FALSE，降低对old的要求，因为约束的意义不大，成不成功，还是看patch还原newzip的文件结果是否正确。

**Comment by linguangyu1996** [comment]
您最近有一次提交改动是fix resign align bug，这个会有什么影响吗？是否有最新的可执行文件呢

**Comment by linguangyu1996** [comment]
有如下操作：
1. build出一个apk，该apk是经过对齐的
2. 使用ApkNormalized进行规范化处理
3. 再使用命令zipalign -c -v 4 apk看到规范化之后的apk是对齐的
4. 使用命令zipalign -v 4 apk newapk对规范化后的apk进行对齐，这时候在用zipalign -c -v 4 newapk，这时候newapk就不是对齐的了

上述第4步骤按照正常来说一个对齐的apk再次执行zipalign -v 4之后也是对齐的才是吧，这是什么原因呢？

谢谢~

**Comment by sisong** [comment]
“fix resign align bug”   这个问题是有人遇到这种情况：apk包在生成时进行过一次签名，然后执行ApkNormalized后再用安卓的SDK中的签名工具又进行了第二次签名； 而这前后二次签名有点不兼容（签名文件的名称被修改和文件对齐方式也被破坏）； 该修复修改了ApkNormalized逻辑（patch流程不受影响）将这些可能被签名修改的文件排序后存储到了apk包的最后面，降低可能被签名过程破坏兼容的可能。 （所以可以发现，这个“耦合”哪天还可能随着签名工具的升级引起兼容问题）

**Comment by sisong** [comment]
“4. 使用命令zipalign -v 4 apk newapk对规范化后的apk进行对齐，这时候在用zipalign -c -v 4 newapk，这时候newapk就不是对齐的了”        
这确实比较奇怪，zipalign执行对齐和立即检查对齐不应该受到ApkNormalized影响；     
ApkNormalized内部选择的是类似-v 8的对齐，不应该再次使用zipalign对齐，这很大可能会破坏“标准化”；

**Comment by linguangyu1996** [comment]
我这边在使用ApkNormalized工具进行V2的时候发现会出现如下问题：

1、apk会出现ERROR: newZip not Normalized, need do newZip=AndroidSDK#apksigner(ApkNormalized(AndroidSDK#apksigner(newZip))) before running ZipDiff!\n 的报错，但是我已经严格按照了newZip=AndroidSDK#apksigner(ApkNormalized(AndroidSDK#apksigner(newZip)))玩法进行过normalized了。

2、上述中会出现报错，但是发现还是能得到md5一致的apk，并且在ZipDiff的过程中最后也有byte to byte equel的输出。

3、查看源码发现其实在v1签名的时候也没有能够正确的判断是进行的normalized的，因为没有输出“NOTE: newZip maybe normalized”这一句日志

请问，什么情况下会出现上述问题吗？

**Comment by sisong** [comment]
1. 猜测是AndroidSDK#apksigner的处理过程破坏了是否是Normalized的检查； 如果方便的话可以邮件给我你的apk，测试看看具体是什么原因破坏的。        
1.  有“byte to byte equel的输出”，意思就是每个字节都相同， 就不用担心patch出来的包不同了；    
1.  normalized标志只是一个提示，并不具有严格意义；特别是包只有v1签名的时候，包中的任何文件都可能被重新压缩和颠倒顺序；
