### ISSUE TITLE
Can I use it for delta patching custom android ROMS?

### ISSUE THREAD

**Issue by arun54321** [sisong/ApkDiffPatch#69]
Or use some other tools for that purpose?

**Comment by sisong** [comment]
> " custom android ROMS "   

is zip format?     if true,try used  ApkDiffPatch

> " other tools "      

for patching binary data, [HDiffPatch](https://github.com/sisong/HDiffPatch), xdelta, bsdiff, jojodiff, ...

**Comment by arun54321** [comment]
android roms are compressed two times. first compression with brotli and second compression with zip, I had to extract the zip and then extract brotli compressed .br files and run xdelta3 on uncompressed files to get good results.
