### ISSUE TITLE
建议andorid release 上传maven

### ISSUE THREAD

**Issue by excitedhaha** [sisong/ApkDiffPatch#70]
如题

**Comment by sisong** [comment]
比其直接在github的releases里下载，maven有什么特别的优势吗？

**Comment by excitedhaha** [comment]
方便很多，gradle一行搞定

**Comment by excitedhaha** [comment]
方便很多，gradle一行搞定，版本升级的时候更明显。跟其他库可以对齐

**Comment by sisong** [comment]
谢谢你的建议和工作流程分享。   
我决定还是保留现在的方式，基于以下的考虑：   
.  patch库的升级我觉得应该是一件“深思熟虑”后的动作，因为它是一个耦合，需要进行严密的兼容性测试才能上线     
.  我给的.so文件可以看作是一个最简单的用例；自己实际使用的时候可以做一些裁剪和定制（比如去掉自己不要的压缩库，去掉old缓存逻辑、修改返回值等等），so编译方式也可以自定义（比如修改链接的库或链接方式等）    
.  这样比较简单
