### ISSUE TITLE
How to create diff and apply patch for android?

### ISSUE THREAD

**Issue by rupeshurmaliya** [sisong/ApkDiffPatch#71]
Hi @sisong, 

I am trying to create diff for android apk and patch. I want to generate the diff in my local macos machine. 

Please help me to do the above or any lead would be appreciated. Thanks in advance.

**Comment by sisong** [comment]
you can Download from latest release : https://github.com/sisong/ApkDiffPatch/releases   
 Command line app for Windows, Linux, MacOS; and .so patch lib for Android.       
    
run diff cmd line on MacOS:      
`$ ZipDiff oldZipFile newZipFile outDiffFileName  ` 
input oldZipFile & newZipFile file can *.zip *.jar *.apk file type;    
run patch cmd line on  MacOS(for test):    
`$ ZipPatch oldZipFile zipDiffFile outNewZipFile [maxUncompressMemory tempUncompressFileName] [-p-parallelThreadNumber]`   
run patch on android:    
add libapkpatch.so & ApkPatch.java to your project;   then call java function ApkPatch.patch:
`int patch(String oldApkPath,String patchFilePath,String outNewApkPath,   
  long maxUncompressMemory,String tempUncompressFilePath,int threadNum);`

**Comment by rupeshurmaliya** [comment]
I am getting this error: `zsh: command not found: ZipDiff` while I am trying to run `ZipDiff oldZipFile newZipFile outDiffFileName`

**Comment by sisong** [comment]
try write:  `./ZipDiff` ?

**Comment by rupeshurmaliya** [comment]
Thanks! It worked. But I am getting this `newZip used ApkV2Sign, but not complete, as an ERROR!`

Also while I am trying to apply the patch getting below error:

j`ava.lang.UnsatisfiedLinkError: No implementation found for int com.android.first.ApkPatch.patch(java.lang.String, java.lang.String, java.lang.String, long, java.lang.String, int) (tried Java_com_android_first_ApkPatch_patch and Java_com_android_first_ApkPatch_patch__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2JLjava_lang_String_2I)`

**Comment by sisong** [comment]
you need read https://github.com/sisong/ApkDiffPatch/blob/master/README.md    
> "if your apk used Apk v2 sign(or Apk v3 sign), Released Apk := AndroidSDK#apksigner(ApkNormalized(AndroidSDK#apksigner(Apk))) before ZipDiff;"       

not loaded lib?  `System.loadLibrary("apkpatch");`

**Comment by rupeshurmaliya** [comment]
This is how I am using in android:

```
private fun apkPatch() {
        val root = filesDir
        val oldApkPath = "$root/1/first.apk"
        val patchFilePath = "$root/1/add.diff"
        val newApkPath = "$root/1/new.apk"
        val maxUncompressMemory: Long = 8 * 1024 * 1024
        val tempUncompressFilePath = "$root/temp/"
        val threadNum = 1
        System.loadLibrary("apkpatch")
        ApkPatch.patch(oldApkPath, patchFilePath, newApkPath, maxUncompressMemory, tempUncompressFilePath, threadNum)
    }
```

**Comment by sisong** [comment]
you run app on arm64,so need:
`arm64-v8a/libapkpatch.so  -> app/src/main/jniLibs/arm64-v8a/libapkpatch.so`

**Comment by rupeshurmaliya** [comment]
What changes should I make here? I am sorry I am new to this.

**Comment by Xbs233** [comment]
> Thanks! It worked. But I am getting this `newZip used ApkV2Sign, but not complete, as an ERROR!`
> 
> Also while I am trying to apply the patch getting below error:
> 
> j`ava.lang.UnsatisfiedLinkError: No implementation found for int com.android.first.ApkPatch.patch(java.lang.String, java.lang.String, java.lang.String, long, java.lang.String, int) (tried Java_com_android_first_ApkPatch_patch and Java_com_android_first_ApkPatch_patch__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2JLjava_lang_String_2I)`

checkout your ApkPatch.java's package name .it should be **com.github.sisong.ApkPatch.java** 
or change the method name of JNI (in apk_patch_jni.cpp) and compile you owm libapkpatch.so

i solve it through that way

**Comment by sisong** [comment]
load lib once, java code in a class：
```
   static {
        System.loadLibrary("apkpatch");
    }
```

**Comment by rupeshurmaliya** [comment]
Thanks for the response. I will check and update here.

**Comment by rupeshurmaliya** [comment]
`System.loadLibrary("apkpatch");` at this line I am getting below error:

`java.lang.UnsatisfiedLinkError: dlopen failed: file offset for the library "/data/app/com.github.sisong-g6E2aqRtCmotMBqtmE9xrA==/lib/arm64/libapkpatch.so" >= file size: 0 >= 0`

**build.gradle**

```
plugins {
    id 'com.android.application'
    id 'kotlin-android'
}

android {
    compileSdkVersion 30
    buildToolsVersion "30.0.0"

    defaultConfig {
        applicationId "com.github.sisong"
        minSdkVersion 21
        targetSdkVersion 30
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }

    sourceSets {
        main {
            jniLibs.srcDir "src/main/jniLibs"
        }
    }
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
    implementation 'androidx.core:core-ktx:1.3.2'
    implementation 'androidx.appcompat:appcompat:1.2.0'
    implementation 'com.google.android.material:material:1.2.1'
    implementation 'androidx.constraintlayout:constraintlayout:2.0.4'
    implementation fileTree(include: ['*.so'], dir: 'jniLibs')
}
```

**MainActivity.kt**

```
class MainActivity : AppCompatActivity() {

    init {
        System.loadLibrary("apkpatch")
    }

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)
        findViewById<MaterialButton>(R.id.applyPatchBtn).setOnClickListener {
            apkPatch()
        }
    }


    private fun apkPatch() {
        val root = filesDir
        val oldApkPath = "$root/1/first.apk"
        val patchFilePath = "$root/1/add.diff"
        val newApkPath = "$root/1/new.apk"
        val maxUncompressMemory: Long = 8 * 1024 * 1024//8mb
        val tempUncompressFilePath = "$root/temp/"
        val threadNum = 1
        ApkPatch.patch(
            oldApkPath,
            patchFilePath,
            newApkPath,
            maxUncompressMemory,
            tempUncompressFilePath,
            threadNum
        )
    }
```

![Screenshot 2021-03-10 at 5 01 49 PM](https://user-images.githubusercontent.com/3490638/110623070-5256f080-81c2-11eb-8af0-e65f79679c69.png)

I changed the package name but still facing this issue. 
@Xbs233 @sisong 
Please help.

**Comment by rupeshurmaliya** [comment]
App is crashing at this point. `System.loadLibrary("apkpatch")`
3. have libapkpatch.so in jniLibs/arm64-v8a/ ? -> Yes 

![Screenshot 2021-03-10 at 5 50 22 PM](https://user-images.githubusercontent.com/3490638/110628506-183d1d00-81c9-11eb-9927-fd3ee628f2a4.png)

**Comment by sisong** [comment]
open this *project's apk file* ,can found /lib/arm64-v8a/libapkpatch.so ?

**Comment by sisong** [comment]
file size error： 2B？

**Comment by rupeshurmaliya** [comment]
Yes it is showing but the file size is 2B

**Comment by rupeshurmaliya** [comment]
```
private fun apkPatch() {
        val root = filesDir
        val oldApkPath = "$root/1/first.apk"
        val patchFilePath = "$root/1/add.diff"
        val newApkPath = "$root/1/new.apk"
        val maxUncompressMemory: Long = 8 * 1024 * 1024//8mb
        val tempUncompressFilePath = "$root/temp/"
        val threadNum = 1
      ApkPatch.patch(oldApkPath, patchFilePath, newApkPath, maxUncompressMemory, tempUncompressFilePath, threadNum)
    }
```

In this as you have mentioned that **tempUncompressFilePath need a fileName like: "$root/temp/apkpatch.tmp"** `tempUncompressFilePath` is the `newApkPath` then why there are two or am I doing something wrong?

Lib file was problem with AS. I copied it again.
@sisong

**Comment by sisong** [comment]
.so file is empty, so you got: `java.lang.UnsatisfiedLinkError: dlopen failed: file offset for the library "/data/app/com.github.sisong-g6E2aqRtCmotMBqtmE9xrA==/lib/arm64/libapkpatch.so" >= file size: 0 >= 0`

**Comment by rupeshurmaliya** [comment]
Also I am creating diff of the apk as below
`./ZipPatch oldFile.apk  tempFile newFile.apk`
and I am using [Apk V2 Sign](https://source.android.com/security/apksigning/v2) 
But as you mentioned that I have to use `Released newZip := AndroidSDK#apksigner(ApkNormalized(AndroidSDK#apksigner(newZip))) before ZipDiff;`
How to use this? Shall I just copy the above command like below?

```
Released newZip := AndroidSDK#apksigner(ApkNormalized(AndroidSDK#apksigner(newZip)))
./ZipPatch oldFile.apk  tempFile newFile.apk
```

@sisong

**Comment by sisong** [comment]
need uncompress some temp data to tempFile from oldFile when uncompress data's size>maxUncompressMemory.

**Comment by sisong** [comment]
apksigner is a cmdline tool in NDK, you need to search "apksigner" how to use it.
