### ISSUE TITLE
Problem with split apks (INSTALL_FAILED_INVALID_APK: Failed to extract native libraries, res=-2)

### ISSUE THREAD

**Issue by kasnder** [sisong/ApkDiffPatch#72]
Hello,

I'm trying to use ZipDiff for the Twitter app.

When downloading for an arm64 device from the German Google Play Store, this comes in 5 .apk files:

- `base.apk`
- `split_config.arm64_v8a.apk`
- `split_config.de.apk`
- `split_config.en.apk`
- `split_config.xxhdpi.apk`

Unfortunately, if I apply `AndroidSDK#apksigner(ApkNormalized(AndroidSDK#apksigner(newZip)))` to `split_config.arm64_v8a.apk` I get the following error when installing with `adb install-multiple *.apk`:

```
adb: failed to finalize session
Failure [INSTALL_FAILED_INVALID_APK: Failed to extract native libraries, res=-2]
```

Installing works without problems if I only apply `AndroidSDK#apksigner(newZip)` to `split_config.arm64_v8a.apk` and `AndroidSDK#apksigner(ApkNormalized(AndroidSDK#apksigner(newZip)))` tothe other .apk files.

**Comment by kasnder** [comment]
I assume that libraries within `split_config.arm64_v8a.apk` are wrongly compressed or aligned after running `ApkNormalized`.

**Comment by kasnder** [comment]
Additionally, I cannot run ZipDiff on `split_config.arm64_v8a.apk` without running `ApkNormalized`.

`ZipDiff split_config.arm64_v8a.apk split_config.arm64_v8a-a.apk split_config.arm64_v8a.ZipDiff` results in:

```
check ZipPatch result Byte By Byte Equal ERROR!
  (did newZip=AndroidSDK#apksigner(ApkNormalized(AndroidSDK#apksigner(newZip))) before running ZipDiff?)
```

**Comment by sisong** [comment]
the cmdline ApkNormalized version is 1.3.6?  
you can make it by yourself:  
```
$cd <ApkdiffPatch>
$make
```

I have't tested with split apks,    
Can you email this file "split_config.arm64_v8a.apk" to me(housisong@hotmail.com)?

**Comment by kasnder** [comment]
Oh, it's 1.3.5. I was using the latest compiled version from the webpage. I'll check again!

**Comment by sisong** [comment]
Possible attempt:  
1. packed apk files to one *.apks (or *.aab) file , and  run apksigner? 
2.  like [bundletool](https://developer.android.google.cn/studio/command-line/bundletool) , signed split apks

**Comment by sisong** [comment]
I Success!   
I test Twritter split apks( base.apk split_config.arm64_v8a.apk split_config.de.apk split_config.en.apk split_config.xxhdpi.apk )     
edit AndroidManifest.xml file in base.apk，change` android:extractNativeLibs="false"` to `android:extractNativeLibs="true"`     
then all apks do ApkNormalized & AndroidSDK#apksigner       
run: `adb install-multiple base.apk split_config.arm64_v8a.apk split_config.de.apk split_config.en.apk split_config.xxhdpi.apk`      
result "Success", and the TWritter app can be run on Android.

**Comment by kasnder** [comment]
Thanks for clarifying! I really don't like the latest changes to the APK format by Google..

**Comment by sisong** [comment]
same don't like

**Comment by sisong** [comment]
now, this lib new version supported page-align uncompressed .so files.
