### ISSUE TITLE
如何在Android设备上二次签名？

### ISSUE THREAD

**Issue by super-h-c** [sisong/ApkDiffPatch#73]
手机上怎么签名呢？需要秘钥签名文件内置到Apk中吗

**Comment by sisong** [comment]
重新签名 是在发布前进行的，（在zipdiff之前）。   不是在手机端patch后

**Comment by super-h-c** [comment]
在apknormalized之后zipdiff之前---apknormalized这个操作针对的是oldApk么，oldApk本身不就已经签名过了吗

**Comment by sisong** [comment]
对外发布的apk都需要经过apknormalized处理

**Comment by sisong** [comment]
流程理解问题，不应该在设备上重新签名，关闭issue

**Comment by super-h-c** [comment]
请问下，重新签名后patch反而变大了。没有重新签名直接生成的patch是400多k，重新签名后生成的反而是1.2M。比google的archive-patcher 的patch包大，与您这边的测试结果好像不符合

**Comment by NiuGuohui** [comment]
> 对外发布的apk都需要经过apknormalized处理

请问一下，如果oldApk已经发布了，那是不是就得先让客户更新到一个normalized oldApk上，才能实现patch一个newApk呀？不改变客户现有情况的话是不是就无法实现patch呀？

**Comment by sisong** [comment]
如果oldapk没有处理过，就不能多线程patch。    
diff时就能会进行patch测试，从而知道是否能够能够正确patch。
