### ISSUE TITLE
ps: 广告，我正在开发一个不需要重新签名的方案[sfpatcher](https://github.com/sisong/sfpatcher),

### ISSUE THREAD

**Issue by super-h-c** [sisong/ApkDiffPatch#75]
ps: 广告，我正在开发一个不需要重新签名的方案[sfpatcher](https://github.com/sisong/sfpatcher),
PC上用你的重新签名后的2个apk测试：diff用时23.49秒创建补丁：486325字节；多线程执行patch打补丁时间0.39秒。

_Originally posted by @sisong in https://github.com/sisong/ApkDiffPatch/issues/74#issuecomment-837868533_

**Comment by super-h-c** [comment]
https://github.com/sisong/sfpatcher  sfpatch 这个库目前可以使用吗？clone下载下来没有代码只有一个readme文件

**Comment by sisong** [comment]
还在最后收尾的开发中
