### ISSUE TITLE
unexpected e_version: 65725

### ISSUE THREAD

**Issue by hamid97m** [sisong/ApkDiffPatch#82]
Hi, I'm trying to add .so libs, but the application crashed with this log:

after this line:
System.loadLibrary("apkpatch")

    java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/~~7FJ6lgx7dsGMWC9xxg1TJg==/{PACKAGE_NAME}-6r1jdKB04eTDrv5z0eGEDw==/lib/arm64/libapkpatch.so" has unexpected e_version: 65725

could you please help me?

**Comment by sisong** [comment]
you changed class ApkPatch's sourceCode path?      
class ApkPatch must in package com.github.sisong;

**Comment by hamid97m** [comment]
No i didn't changed anything, I just put the .so files in my project from this [releaes](https://github.com/sisong/ApkDiffPatch/releases/download/v1.4.0/ApkDiffPatch_v1.4.0_bin_test.zip) and then call 

    System.loadLibrary("apkpatch")

**Comment by sisong** [comment]
I have an xiaomi android 12 phone;  I download and retest it on this phone, all it's ok.

**Comment by hamid97m** [comment]
Could you please share the sample project?

**Comment by hamid97m** [comment]
Did you call `System.loadLibrary("apkpatch") `?

**Comment by sisong** [comment]
yes       
call once

**Comment by sisong** [comment]
why dlopen failed?

**Comment by hamid97m** [comment]
I just test in a new project and everything worked! so I trying to find out the problem with my project.
Thank you.
