### ISSUE TITLE
Patch 过程中 4*(decompress stream memory) 这部分内存有办法降低吗？在手机设备上执行内存比较紧张？

### ISSUE THREAD

**Issue by ityancs** [sisong/ApkDiffPatch#86]

**Comment by sisong** [comment]
1. 最简单的方案：diff的时候控制一下压缩字典大小，比如4MB或8MB； 一般手机应该都没有问题了。      
2. 替换使用的diff&patch算法，比如将 程序中默认调用的diff函数  `create_compressed_diff_block()` 替换为 `create_single_compressed_diff_block()`，程序中默认调用的patch函数   `patch_decompress_with_cache()` 替换为 `patch_single_stream()`；   这样替换后，Patch内存就是 stepSize+1*(decompress stream memory);   
3. 还需要注意：2 只是解决了单线程patch的内存的占用问题；而apkpatch的多线程patch时内存优化并不好，会占用非常多的内存，你需要测试。  （而[sfpatcher](https://github.com/sisong/sfpatcher)方案才解决了这个问题支持平均O(1)内存的多线程patch。）

**Comment by ityancs** [comment]
> 
大佬，修改后卡在 getCompressedDiffInfo 了，能辛苦提供个替换算法方案的 demo 吗？

run ZipPatch:
getCompressedDiffInfo(&diffInfo,zipDiffData.hdiffzData) PATCH_HDIFFINFO_ERROR!

**Comment by sisong** [comment]
换成 getSingleCompressedDiffInfo

**Comment by sisong** [comment]
我计划添加该特性，支持单压缩流
