### ISSUE TITLE
测试发现 patch 最大的耗时还是在将 new apk 的数据部分压缩，想要直接生成压缩等级为 0 的 new apk，求问大佬有什么办法嘛

### ISSUE THREAD

**Issue by Candyerer** [sisong/ApkDiffPatch#88]

**Comment by sisong** [comment]
`$ApkNormalized -cl-compressLevel ...` 支持重新设置压缩等级，现在开放 1--9，没有0，你可以改改。      
这样处理完的话，apk文件会比较大，并且不再需要ZipDiff，而是可以直接使用hdiffz来生成增量包了。
