### ISSUE TITLE
Problem with split apks (INSTALL_FAILED_INVALID_APK: Failed to extract native libraries, res=-2)

### ISSUE THREAD

**Issue by DonaldDu** [sisong/ApkDiffPatch#91]
ApkNormalized后，再重新签名后。有些正常，有些不正常。刚好又遇到一个能复现的。
复现步骤：
下载[APK(URL)](https://gitee.com/DonaldDu/tmp/blob/master/survey-debug.apk)，然后执行ApkNormalized，再签名，然后安装应用。

就能复现上面的问题。

**Comment by DonaldDu** [comment]
没上传签名KEY，随便弄个签名即可

**Comment by sisong** [comment]
谢谢提供的信息。  我会很快跟进

**Comment by sisong** [comment]
能够复现，问题还在查找中

**Comment by sisong** [comment]
@DonaldDu    
知道原因了：   
这个apk的AndroidManifest.xml中设置了android:extractNativeLibs=false   
而apk文件中的.so文件没有压缩； 那按安卓要求这些.so文件在apk中的开始位置必须按内存页面大小对齐。     
比如用 ApkNormalized.exe  -as-4k ... 处理，就可以测试通过；但不建议这样做，apk文件会变的较大。   
   
可能的处理方案：   
1. 设置android:extractNativeLibs=true ,  压缩所有.so; 这样就没有兼容性问题了，apk包也会小一些。
1. 修改Normalize代码，根据前面提到的条件，自动按要求对齐.so文件到4k页面；patch端也需要更新才能兼容。

**Comment by sisong** [comment]
这个问题和 #72 完全一样

**Comment by sisong** [comment]
现在新版本已经支持按页面对齐为压缩.so文件了。  需要更新patch端。
