### ISSUE TITLE
ZipDiff zip file failed if zip > 4G

### ISSUE THREAD

**Issue by zminy121** [sisong/ApkDiffPatch#94]
使用该工程，编译出ZipDiff,  ZipPatch. 如果zip文件< 4G,能正常差分还原，但是如果zip > 4G, ，则不能进行差分。
我试着将工程中int-->uint64_t, 但是几乎每个接口都会报错，现在卡在check(kCENTRALHEADERMAGIC == readUInt32(headBuf));不知如何修改了。
请问大神，这个工程会优化适配> 4G的差分还原吗？

**Comment by sisong** [comment]
并不是简单修改 int-->uint64_t 就能支持大于4G的zip包； 而是需要支持 zip64 格式。     
你可以试试 [sfpatcher](https://github.com/sisong/sfpatcher/releases) 项目, 它应该支持zip64格式。   

一直没有给该项目添加zip64支持，是因为现在最大的apk包应该还在2.5G以内； 而且安卓的开发工具好像也没有支持zip64。
