### ISSUE TITLE
Product size 0 on windows

### ISSUE THREAD

**Issue by 793383996** [sisong/ApkDiffPatch#98]
Product size 0 on windows
![image](https://github.com/user-attachments/assets/09b22fe2-a450-47a5-95d4-420285c7db5d)
![image](https://github.com/user-attachments/assets/6dc80dff-4ac0-4622-a827-ec79df4123d5)
![image](https://github.com/user-attachments/assets/419f9183-64f2-418d-b798-a9ad2ace03a3)

**Comment by sisong** [comment]
程序没有结束吧? 需要等一下下
